
from .segmentation import dibco_binarization_fn, diva_post_processing_fn, page_post_processing_fn
from .line_detection import cbad_post_processing_fn
from .boxes_detection import cini_post_processing_fn