from .DIVA.diva_post_processing import diva_post_processing_fn
from .Ornaments.ornaments_post_processing import ornaments_post_processing_fn
from .Page.page_post_processing import page_post_processing_fn
from .cBAD.cbad_post_processing import cbad_post_processing_fn
from .DIBCO.dibco_post_processing import dibco_binarization_fn
#from .Cini.cini_post_processing import cini_post_processing_fn
from .DIVA.diva_evaluation import diva_evaluate_folder
#from .Cini.cini_evaluation import cini_evaluate_folder
from .cBAD.cbad_evaluation import cbad_evaluate_folder
from .DIBCO.dibco_evaluation import dibco_evaluate_folder
from .Ornaments.ornaments_evaluation import ornament_evaluate_folder
from .Page.page_evaluation import page_evaluate_folder
from .evaluation.base import evaluate_epoch